[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["Agent", "Model", "Provider", "Vendor/Deepseek", "Area/AI", "Type/Connector"]
license = ["Apache-2.0"]
icon="icon.png"
name = "ai.deepseek"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.deepseek"
version = "1.1.1"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "ai.deepseek-native"
version = "1.1.1"
path = "../native/build/libs/ai.deepseek-native-1.1.1.jar"
