[plugin]
id = "ai-deepseek-compiler-plugin"
class = "io.ballerina.lib.ai.deepseek.AiDeepseekCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/ai.deepseek-compiler-plugin-1.0.2-SNAPSHOT.jar"

[[dependency]]
path = "../compiler-plugin/build/libs/ballerina-to-openapi-2.3.0.jar"
